################################################################################
#                                                                              #
#                           Custom Daytime Plugin                              #
#                                                                              #
#     Created by Seedim (https://github.com/SeedimV)                           #
#                                                                              #
#     This plugin lets you customize the length of day and night cycles,       #
#     and replaces the usual sleep-to-skip-night mechanic with a smooth        #
#     acceleration of time when enough players sleep.                          #
#                                                                              #
#     Licensed under the GPL-3.0 License.                                      #
#                                                                              #
#     Check out my projects on https://modrinth.com/user/SeedimV.              #
#                                                                              #
################################################################################

"minecraft:overworld" {
    # Length of the daytime cycle in minutes
    # Default: 10.0
    dayLength=10.0

    # Length of the nighttime cycle in minutes
    # Default: 10.0
    nightLength=10.0

    # Enable or disable night acceleration when enough players sleep
    # False: use vanilla sleep-to-skip-night mechanic
    # Default: true
    accelerationEnabled=true

    # Multiplier for night acceleration during sleep
    # Example: nightLength=10.0 (= 600 seconds) and AccelerationMultiplier=100.0 -> Acceleration lasts 6 seconds
    # Default: 100.0
    AccelerationMultiplier=100.0
}